language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: RDKhEaZOi8DuZMVqsDMWYyBIXmrQXbeIA1d3LkM512NoCNcXDGTRGX7HJ9guFdwRKWrtUE5os6EcaS4TCh5Okq2UlrX7SwuvyCARgWoMT4avN9QwU9Xtx4asU8+FKZOFNiR4OflZLc3BmyxLFLu2qtcDD9FUpTDkWlU5AYmW2Q51RNTkw3cW4IrPMbtmrWstjG/ghR7rOwtt4WsaCEMaO93DF6YYVuRQmad2c092wLTUYDpHu9cjVJAXeINhG3jonwCENoWWlHEsdIYKedRT1AuUfXrLCoYFLYSO8jD7ATPx3lGFRoT778usHN2Ikc3tb5yBm33IBGux4Ixs9t2xlhEJZS0RT7/DRkYQqGiozOYXUeauQg1FDMehCL6S97XR6tpywa0gF8AbJnlWuA3KMN0SjiVSrhqP9nTb+LWjyjzZ+JPMt0JVl7+p17fDQWTvdtw9JC3wyhrzhlYzl6ZMZ5jrGtPZWhSitD8PEIZDzr5K9NIf4EfFLaLoXccH10IvAzA7ihzt7BiknJivSMrv1kNfHStqT23iVnK9tnv1ggs1x+qXHHtYsZe9aVLc8TO5nEq/LMhylbFENRYTR62F4sgOEiq2wn465p89RxPJpNalEAnVkIdpb0dOHErHDysCXNVosloYfSeCvTtd+luX199TwoL+lL1qtI8p50ppJM8=
  app: glacial-taiga-70430
  on:
    repo: zipofar/funbox-test-2
